//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhmadTaheri.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kexp
    {
        public int Id { get; set; }
        public Nullable<double> Kexp1 { get; set; }
        public Nullable<double> Kexp2 { get; set; }
        public Nullable<double> Kexp3 { get; set; }
        public Nullable<double> Kexp4 { get; set; }
        public Nullable<double> Kexp5 { get; set; }
        public Nullable<double> Kexp6 { get; set; }
        public Nullable<double> Kexp7 { get; set; }
        public Nullable<double> Kexp8 { get; set; }
        public Nullable<double> Kexp9 { get; set; }
        public Nullable<double> Kexp10 { get; set; }
        public Nullable<double> Kexp11 { get; set; }
        public Nullable<double> Kexp12 { get; set; }
        public Nullable<double> Kexp13 { get; set; }
        public Nullable<double> Kexp14 { get; set; }
        public Nullable<double> Kexp15 { get; set; }
    }
}
