//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhmadTaheri.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMC
    {
        public int Id { get; set; }
        public Nullable<double> KMC1 { get; set; }
        public Nullable<double> KMC2 { get; set; }
        public Nullable<double> KMC3 { get; set; }
        public Nullable<double> KMC4 { get; set; }
        public Nullable<double> KMC5 { get; set; }
        public Nullable<double> KMC6 { get; set; }
        public Nullable<double> KMC7 { get; set; }
        public Nullable<double> KMC8 { get; set; }
        public Nullable<double> KMC9 { get; set; }
        public Nullable<double> KMC10 { get; set; }
        public Nullable<double> KMC11 { get; set; }
        public Nullable<double> KMC12 { get; set; }
        public Nullable<double> KMC13 { get; set; }
        public Nullable<double> KMC14 { get; set; }
        public Nullable<double> KMC15 { get; set; }
    }
}
