//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhmadTaheri.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class N
    {
        public int Id { get; set; }
        public Nullable<double> NIA { get; set; }
        public Nullable<double> NIC { get; set; }
        public Nullable<double> NIS { get; set; }
        public Nullable<double> NM { get; set; }
        public Nullable<double> NR { get; set; }
        public Nullable<double> NCTA { get; set; }
        public Nullable<double> NP { get; set; }
        public Nullable<double> NPsec { get; set; }
        public Nullable<double> NPtert { get; set; }
        public Nullable<double> ND { get; set; }
        public Nullable<double> NDprime { get; set; }
        public Nullable<double> NSCB { get; set; }
        public Nullable<double> NLCB { get; set; }
    }
}
