//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhmadTaheri.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prk
    {
        public int Id { get; set; }
        public Nullable<double> Prk1 { get; set; }
        public Nullable<double> Prk2 { get; set; }
        public Nullable<double> Prk3 { get; set; }
        public Nullable<double> Prk4 { get; set; }
        public Nullable<double> Prk5 { get; set; }
        public Nullable<double> Prk6 { get; set; }
        public Nullable<double> Prk7 { get; set; }
        public Nullable<double> Prk8 { get; set; }
        public Nullable<double> Prk9 { get; set; }
        public Nullable<double> Prk10 { get; set; }
        public Nullable<double> Prk11 { get; set; }
        public Nullable<double> Prk12 { get; set; }
        public Nullable<double> Prk13 { get; set; }
        public Nullable<double> Prk14 { get; set; }
        public Nullable<double> Prk15 { get; set; }
    }
}
