//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhmadTaheri.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReactionNumber
    {
        public int Id { get; set; }
        public int ReactionNumber1 { get; set; }
    }
}
