//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhmadTaheri.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMC
    {
        public int Id { get; set; }
        public Nullable<double> RMC1 { get; set; }
        public Nullable<double> RMC2 { get; set; }
        public Nullable<double> RMC3 { get; set; }
        public Nullable<double> RMC4 { get; set; }
        public Nullable<double> RMC5 { get; set; }
        public Nullable<double> RMC6 { get; set; }
        public Nullable<double> RMC7 { get; set; }
        public Nullable<double> RMC8 { get; set; }
        public Nullable<double> RMC9 { get; set; }
        public Nullable<double> RMC10 { get; set; }
        public Nullable<double> RMC11 { get; set; }
        public Nullable<double> RMC12 { get; set; }
        public Nullable<double> RMC13 { get; set; }
        public Nullable<double> RMC14 { get; set; }
        public Nullable<double> RMC15 { get; set; }
        public Nullable<double> SumRMC { get; set; }
    }
}
